services:
  - type: web
    name: pdfhub
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      aptPackages:
        - libglib2.0-dev
        - libcairo2-dev
        - libpango1.0-dev
        - libgdk-pixbuf2.0-dev
        - libffi-dev
        - libxml2-dev
        - libxslt1-dev
        - zlib1g-dev
        - libjpeg-dev
        - build-essential
