services:
  - type: web
    name: pdfhub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    runtime: python
    pythonVersion: 3.10
